version: "3"

services:
  django_app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - static:/code/static
      - ./media:/code/media
      - .:/code

  nginx:
    image: nginx:1.13
    ports:
      - 8687:80
    labels:
      - "traefik.http.routers.nginx.rule=Host(`nginx.localhost`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/code/static
      - ./media:/code/media
    depends_on:
      - django_app

  traefik:
    image: traefik:v2.9
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  postgres_data:
  static:

