version: "3"

services:
  django_app:
    build: .
    volumes:
      - static:/code/static
      - ./media:/code/media
      - .:/code

  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/code/static
      - ./media:/code/media
    depends_on:
      - django_app

volumes:
  postgres_data:
  static:

